import React, { useState, useEffect } from 'react';
import {
  FileText,
  Sparkles,
  CheckCircle2,
  AlertTriangle,
  XCircle,
  Copy,
  Download,
  Play,
  Save,
  ShieldCheck,
  RotateCcw,
  Eye,
  Check,
  ArrowRight,
  Plus,
  Wand2,
  Lightbulb
} from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { ScriptItem, GameSpecification, ValidationResult } from '../../types';
import { validateGameSpecification } from '../../utils/validator';
import { SoundEngine } from '../../utils/soundEffects';
import { GeminiScriptScaffoldModal } from './GeminiScriptScaffoldModal';

export const ScriptEditor: React.FC = () => {
  const { scripts, saveScript, saveGame, updateGameStatus, games, setAdminTab } = useApp();

  // Selected or active script
  const [selectedScriptId, setSelectedScriptId] = useState<string>(
    scripts[0]?.id || ''
  );

  const activeScript = scripts.find((s) => s.id === selectedScriptId) || scripts[0];

  // Editable script metadata & text
  const [title, setTitle] = useState(activeScript?.title || '');
  const [minAge, setMinAge] = useState(activeScript?.ageRange?.min || 11);
  const [maxAge, setMaxAge] = useState(activeScript?.ageRange?.max || 15);
  const [durationMinutes, setDurationMinutes] = useState(activeScript?.durationMinutes || 3);
  const [objectives, setObjectives] = useState(activeScript?.objectives || '');
  const [constructs, setConstructs] = useState<string[]>(activeScript?.constructs || ['Prioritization', 'Planning']);
  const [rawScript, setRawScript] = useState(activeScript?.rawScript || '');

  // Generated Game Spec JSON & validation state
  const [generatedSpec, setGeneratedSpec] = useState<GameSpecification | null>(
    activeScript?.generatedSpec || null
  );
  const [specJsonText, setSpecJsonText] = useState<string>('');
  const [validationResult, setValidationResult] = useState<ValidationResult | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isCopied, setIsCopied] = useState(false);
  const [adminStatus, setAdminStatus] = useState<ScriptItem['status']>(activeScript?.status || 'draft');

  // Gemini Script Scaffold Generator Modal & Quick Keyword State
  const [isScaffoldModalOpen, setIsScaffoldModalOpen] = useState(false);
  const [inlineKeywords, setInlineKeywords] = useState('');
  const [isGeneratingInline, setIsGeneratingInline] = useState(false);
  const [scaffoldSuccessNotice, setScaffoldSuccessNotice] = useState<string | null>(null);

  // Sync state when selectedScriptId changes
  useEffect(() => {
    if (activeScript) {
      setTitle(activeScript.title);
      setMinAge(activeScript.ageRange.min);
      setMaxAge(activeScript.ageRange.max);
      setDurationMinutes(activeScript.durationMinutes);
      setObjectives(activeScript.objectives);
      setConstructs(activeScript.constructs);
      setRawScript(activeScript.rawScript);
      setAdminStatus(activeScript.status);

      // Check if there is already a corresponding game in games list or activeScript
      const existingGame = games.find((g) => g.gameId === activeScript.id || g.scriptId === activeScript.id);
      if (existingGame) {
        setGeneratedSpec(existingGame);
        setSpecJsonText(JSON.stringify(existingGame, null, 2));
        setValidationResult(validateGameSpecification(existingGame));
      } else if (activeScript.generatedSpec) {
        setGeneratedSpec(activeScript.generatedSpec);
        setSpecJsonText(JSON.stringify(activeScript.generatedSpec, null, 2));
        setValidationResult(validateGameSpecification(activeScript.generatedSpec));
      } else {
        setGeneratedSpec(null);
        setSpecJsonText('');
        setValidationResult(null);
      }
    }
  }, [selectedScriptId]);

  // When JSON text is manually edited in the Center column, revalidate in real-time
  const handleJsonChange = (newText: string) => {
    setSpecJsonText(newText);
    try {
      const parsed = JSON.parse(newText);
      setGeneratedSpec(parsed);
      setValidationResult(validateGameSpecification(parsed));
    } catch {
      setValidationResult({
        isValid: false,
        schemaValid: false,
        safetyValid: false,
        referencesValid: false,
        toolkitValid: false,
        errors: ['Lỗi cú pháp JSON: Vui lòng kiểm tra dấu phẩy hoặc dấu ngoặc đóng.'],
        warnings: []
      });
    }
  };

  // Apply Scaffold generated by Gemini
  const handleApplyScaffold = (scaffold: {
    title: string;
    objectives: string;
    constructs: string[];
    durationMinutes: number;
    rawScript: string;
    summary?: string;
  }) => {
    setTitle(scaffold.title);
    setObjectives(scaffold.objectives);
    setConstructs(scaffold.constructs);
    setDurationMinutes(scaffold.durationMinutes || 3);
    setRawScript(scaffold.rawScript);

    if (activeScript) {
      const updated: ScriptItem = {
        ...activeScript,
        title: scaffold.title,
        objectives: scaffold.objectives,
        constructs: scaffold.constructs,
        durationMinutes: scaffold.durationMinutes || 3,
        rawScript: scaffold.rawScript,
        status: 'draft',
        updatedAt: new Date().toISOString()
      };
      saveScript(updated);
    }

    setScaffoldSuccessNotice(`✨ Đã nạp khung kịch bản "${scaffold.title}" từ Google Gemini!`);
    setTimeout(() => setScaffoldSuccessNotice(null), 5000);
    SoundEngine.playSuccess();
  };

  // Quick inline generation from keywords
  const handleInlineQuickGenerate = async (keywordsToUse?: string) => {
    const kw = (keywordsToUse || inlineKeywords).trim();
    if (!kw) {
      alert('Vui lòng nhập từ khóa chủ đề (ví dụ: trì hoãn ôn thi, lướt tiktok khuya, áp lực điểm số...)');
      return;
    }

    setIsGeneratingInline(true);
    SoundEngine.playSelect();

    try {
      const response = await fetch('/api/ai/generate-script-scaffold', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          topicKeywords: kw,
          ageRange: { min: Number(minAge), max: Number(maxAge) },
          durationMinutes: Number(durationMinutes),
          selectedConstructs: constructs
        })
      });

      const data = await response.json();
      if (!response.ok || data.error) {
        throw new Error(data.error || 'Lỗi tạo khung kịch bản');
      }

      if (data.scaffold) {
        handleApplyScaffold(data.scaffold);
      }
    } catch (err: any) {
      console.error('Error generating inline scaffold:', err);
      alert('Không thể tạo kịch bản: ' + err.message);
    } finally {
      setIsGeneratingInline(false);
    }
  };

  // AI Game Designer Studio Action (Gemini API)
  const handleGenerateSpec = async () => {
    setIsGenerating(true);
    SoundEngine.playSelect();

    try {
      const response = await fetch('/api/ai/design-game', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title,
          rawScript,
          ageRange: { min: Number(minAge), max: Number(maxAge) },
          durationMinutes: Number(durationMinutes),
          constructs,
          objectives
        })
      });

      const data = await response.json();
      if (data.spec) {
        const spec = {
          ...data.spec,
          scriptId: activeScript.id,
          status: 'draft'
        };
        setGeneratedSpec(spec);
        const formatted = JSON.stringify(spec, null, 2);
        setSpecJsonText(formatted);
        const val = validateGameSpecification(spec);
        setValidationResult(val);

        // Update script item
        saveScript({
          ...activeScript,
          title,
          ageRange: { min: Number(minAge), max: Number(maxAge) },
          durationMinutes: Number(durationMinutes),
          objectives,
          constructs,
          rawScript,
          status: 'review',
          generatedSpec: spec,
          updatedAt: new Date().toISOString()
        });

        SoundEngine.playSuccess();
      }
    } catch (err: any) {
      console.error('Error generating game spec:', err);
      alert('Lỗi tạo Game Specification: ' + err.message);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleSaveDraft = () => {
    if (!activeScript) return;
    const updated: ScriptItem = {
      ...activeScript,
      title,
      ageRange: { min: Number(minAge), max: Number(maxAge) },
      durationMinutes: Number(durationMinutes),
      objectives,
      constructs,
      rawScript,
      status: 'draft',
      generatedSpec: generatedSpec || undefined,
      updatedAt: new Date().toISOString()
    };
    saveScript(updated);
    setAdminStatus('draft');
    SoundEngine.playClick();
    alert('Đã lưu bản nháp kịch bản thành công!');
  };

  const handleSubmitReview = () => {
    if (!activeScript) return;
    saveScript({
      ...activeScript,
      status: 'review',
      updatedAt: new Date().toISOString()
    });
    setAdminStatus('review');
    SoundEngine.playSelect();
    alert('Đã chuyển kịch bản sang trạng thái Chờ Duyệt (Review).');
  };

  const handleApprove = () => {
    if (!generatedSpec || !validationResult?.isValid) {
      alert('Không thể phê duyệt do Game Specification chưa đạt chuẩn schema hoặc có lỗi an toàn.');
      return;
    }
    const approvedSpec: GameSpecification = {
      ...generatedSpec,
      status: 'approved',
      safety: {
        ...generatedSpec.safety,
        status: 'approved',
        reviewerNotes: 'Đã kiểm duyệt đạt chuẩn an toàn nội dung giáo dục.'
      },
      approvedBy: 'Admin Principal'
    };
    setGeneratedSpec(approvedSpec);
    setSpecJsonText(JSON.stringify(approvedSpec, null, 2));
    saveGame(approvedSpec);

    saveScript({
      ...activeScript,
      status: 'approved',
      approvedBy: 'Admin Principal',
      updatedAt: new Date().toISOString()
    });
    setAdminStatus('approved');
    SoundEngine.playSuccess();
    alert('Kịch bản và Game Specification đã được Phê Duyệt thành công!');
  };

  const handlePublish = () => {
    if (!generatedSpec || !validationResult?.isValid || generatedSpec.safety?.status !== 'approved') {
      alert('Cổng xuất bản bị khóa! Kịch bản phải được Schema Validator và An Toàn kiểm tra đạt 100%.');
      return;
    }

    const publishedSpec: GameSpecification = {
      ...generatedSpec,
      status: 'published',
      publishedAt: new Date().toISOString()
    };

    saveGame(publishedSpec);
    saveScript({
      ...activeScript,
      status: 'published',
      publishedAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    });
    setAdminStatus('published');
    SoundEngine.playSuccess();
    alert('🎉 Kịch bản đã được XUẤT BẢN lên Game Runtime! Học sinh có thể trải nghiệm ngay.');
  };

  const handleCopyJson = () => {
    navigator.clipboard.writeText(specJsonText);
    setIsCopied(true);
    setTimeout(() => setIsCopied(false), 2000);
  };

  const handleDownloadJson = () => {
    const blob = new Blob([specJsonText], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${generatedSpec?.gameId || 'game_specification'}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleConstructToggle = (c: string) => {
    if (constructs.includes(c)) {
      setConstructs(constructs.filter((item) => item !== c));
    } else {
      setConstructs([...constructs, c]);
    }
  };

  const handleCreateNewScript = () => {
    const newId = `script_${Date.now()}`;
    const newScript: ScriptItem = {
      id: newId,
      title: 'Kịch bản trải nghiệm mới',
      ageRange: { min: 11, max: 15 },
      durationMinutes: 3,
      objectives: 'Rèn luyện khả năng lựa chọn ưu tiên và kiểm soát hành vi dưới áp lực.',
      constructs: ['Prioritization', 'SelfRegulation'],
      rawScript: `Bối cảnh: Học sinh đang chuẩn bị cho buổi thuyết trình nhóm ngày mai thì nhận được lời mời tham gia giải đấu thể thao điện tử kéo dài cả buổi tối.
Nhân vật: Nam (học sinh lớp 8) và nhóm bạn thân.
Tình huống lựa chọn:
Lựa chọn A: Tham gia giải đấu cùng bạn, dự định thức khuya làm bài sau.
Lựa chọn B: Lịch sự từ chối giải đấu để hoàn thành bài thuyết trình đúng hẹn.
Lựa chọn C: Vừa chơi vừa mở máy làm dở dang, dẫn đến cả hai việc đều dở dang.
Hậu quả tương ứng cho từng lựa chọn và các bước can thiệp tâm lý.`,
      status: 'draft',
      version: '1.0.0',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    };
    saveScript(newScript);
    setSelectedScriptId(newId);
    SoundEngine.playSelect();
  };

  return (
    <div className="space-y-6">
      {/* Top Header & Script Selector */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-white p-5 rounded-2xl border border-gray-200 shadow-2xs">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-indigo-600 text-white flex items-center justify-center font-bold">
            <FileText className="w-5 h-5" />
          </div>
          <div>
            <h2 className="text-lg font-bold text-gray-900">
              Trình Soạn Thảo & Game Design Studio
            </h2>
            <p className="text-xs text-gray-500">
              Chuyển hóa kịch bản thô thành Game Specification JSON tuân thủ chuẩn DSL
            </p>
          </div>
        </div>

        {/* Script Switcher & New Script Button */}
        <div className="flex items-center gap-3 flex-wrap">
          <button
            onClick={() => {
              SoundEngine.playSelect();
              setIsScaffoldModalOpen(true);
            }}
            className="px-3 py-2 bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-700 hover:to-purple-700 text-white text-xs font-bold rounded-xl shadow-xs transition flex items-center gap-1.5 cursor-pointer"
          >
            <Sparkles className="w-3.5 h-3.5 text-amber-300" />
            <span>Google Gemini: Tạo khung kịch bản</span>
          </button>

          <button
            onClick={handleCreateNewScript}
            className="px-3 py-2 bg-indigo-50 hover:bg-indigo-100 text-indigo-700 text-xs font-semibold rounded-xl border border-indigo-200 transition flex items-center gap-1.5 cursor-pointer"
          >
            <Plus className="w-3.5 h-3.5" />
            <span>Thêm kịch bản mới</span>
          </button>
          <div className="flex items-center gap-2">
            <span className="text-xs text-gray-500 font-medium">Chọn:</span>
            <select
              value={selectedScriptId}
              onChange={(e) => setSelectedScriptId(e.target.value)}
              className="text-xs font-semibold py-2 px-3 bg-gray-50 border border-gray-300 rounded-xl focus:ring-2 focus:ring-indigo-500 outline-none"
            >
              {scripts.map((s) => (
                <option key={s.id} value={s.id}>
                  {s.title} [{s.status}]
                </option>
              ))}
            </select>
          </div>
        </div>
      </div>

      {/* Structured Metadata Editor Bar */}
      <div className="bg-white p-5 rounded-2xl border border-gray-200 shadow-2xs space-y-4">
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          <div>
            <label className="block text-xs font-semibold text-gray-700 mb-1">
              Tiêu đề kịch bản
            </label>
            <input
              type="text"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              className="w-full text-xs p-2.5 rounded-lg border border-gray-300 focus:ring-2 focus:ring-indigo-500 outline-none"
            />
          </div>

          <div>
            <label className="block text-xs font-semibold text-gray-700 mb-1">
              Độ tuổi học sinh: {minAge} - {maxAge} tuổi
            </label>
            <div className="flex items-center gap-2">
              <input
                type="number"
                min={6}
                max={maxAge}
                value={minAge}
                onChange={(e) => setMinAge(Number(e.target.value))}
                className="w-16 text-xs p-2 rounded-lg border border-gray-300 text-center"
              />
              <span className="text-gray-400 text-xs">đến</span>
              <input
                type="number"
                min={minAge}
                max={22}
                value={maxAge}
                onChange={(e) => setMaxAge(Number(e.target.value))}
                className="w-16 text-xs p-2 rounded-lg border border-gray-300 text-center"
              />
            </div>
          </div>

          <div>
            <label className="block text-xs font-semibold text-gray-700 mb-1">
              Thời lượng micro-game (1-5 phút)
            </label>
            <input
              type="number"
              min={1}
              max={5}
              value={durationMinutes}
              onChange={(e) => setDurationMinutes(Number(e.target.value))}
              className="w-full text-xs p-2.5 rounded-lg border border-gray-300"
            />
          </div>

          <div>
            <label className="block text-xs font-semibold text-gray-700 mb-1">
              Mục tiêu can thiệp
            </label>
            <input
              type="text"
              value={objectives}
              onChange={(e) => setObjectives(e.target.value)}
              placeholder="VD: Rèn luyện kỹ năng ưu tiên..."
              className="w-full text-xs p-2.5 rounded-lg border border-gray-300"
            />
          </div>
        </div>

        {/* Constructs Selection */}
        <div>
          <label className="block text-xs font-semibold text-gray-700 mb-1.5">
            Constructs tâm lý học đường:
          </label>
          <div className="flex flex-wrap gap-1.5">
            {[
              'Prioritization',
              'Planning',
              'SelfRegulation',
              'ProblemSolving',
              'ConsequencePrediction',
              'Communication',
              'TimeManagement',
              'HelpSeeking',
              'Reflection'
            ].map((c) => {
              const isSelected = constructs.includes(c);
              return (
                <button
                  key={c}
                  type="button"
                  onClick={() => handleConstructToggle(c)}
                  className={`text-[11px] px-2.5 py-1 rounded-lg font-medium transition ${
                    isSelected
                      ? 'bg-indigo-600 text-white shadow-2xs'
                      : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
                  }`}
                >
                  {c}
                </button>
              );
            })}
          </div>
        </div>
      </div>

      {/* Action Trigger Banner */}
      <div className="bg-gradient-to-r from-slate-900 to-indigo-950 p-4 rounded-2xl text-white flex flex-col sm:flex-row items-center justify-between gap-4 shadow-sm">
        <div className="flex items-center gap-3">
          <Sparkles className="w-5 h-5 text-indigo-400 flex-shrink-0 animate-pulse" />
          <span className="text-xs text-slate-300">
            Sử dụng <strong>Google AI Studio / Gemini 3.8 Flash</strong> để phân tích bối cảnh kịch bản và tự động tạo cấu trúc scenes, choices, consequences, và toolkit interventions.
          </span>
        </div>

        <button
          onClick={handleGenerateSpec}
          disabled={isGenerating}
          className="px-6 py-2.5 bg-indigo-500 hover:bg-indigo-600 text-white font-bold text-xs rounded-xl shadow-md transition flex items-center gap-2 flex-shrink-0 cursor-pointer disabled:opacity-50"
        >
          <Sparkles className={`w-4 h-4 ${isGenerating ? 'animate-spin' : ''}`} />
          <span>
            {isGenerating ? 'AI Studio đang phân tích...' : 'Phân tích Script → Tạo Game Specification'}
          </span>
        </button>
      </div>

      {/* 3-COLUMN REVIEW SCREEN (Required by Specification) */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* COLUMN 1: ORIGINAL SCRIPT (Left - 4 cols) */}
        <div className="lg:col-span-4 bg-white p-5 rounded-2xl border border-gray-200 shadow-2xs flex flex-col justify-between space-y-4">
          <div>
            <div className="flex items-center justify-between border-b border-gray-100 pb-3 mb-3">
              <span className="text-xs font-bold uppercase tracking-wider text-gray-700">
                1. Kịch bản gốc (Admin Script)
              </span>
              <span className="text-[11px] text-gray-400">
                {rawScript.length} ký tự
              </span>
            </div>

            {/* AI Scenario Scaffolding Toolbar */}
            <div className="p-3.5 bg-gradient-to-br from-indigo-50/80 via-purple-50/50 to-white rounded-2xl border border-indigo-200/80 space-y-2.5 mb-3 shadow-2xs">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-1.5 font-bold text-indigo-950 text-xs">
                  <Sparkles className="w-3.5 h-3.5 text-indigo-600" />
                  <span>Tạo kịch bản theo từ khóa (Gemini AI)</span>
                </div>
                <button
                  type="button"
                  onClick={() => {
                    SoundEngine.playClick();
                    setIsScaffoldModalOpen(true);
                  }}
                  className="text-[11px] font-semibold text-indigo-700 hover:text-indigo-900 underline cursor-pointer"
                >
                  Mở Studio Nâng Cao
                </button>
              </div>

              <div className="flex items-center gap-1.5">
                <input
                  type="text"
                  value={inlineKeywords}
                  onChange={(e) => setInlineKeywords(e.target.value)}
                  placeholder="Nhập từ khóa chủ đề (VD: 'trì hoãn', 'lướt điện thoại khuya')..."
                  className="flex-1 text-xs p-2 rounded-xl border border-indigo-200 bg-white focus:ring-2 focus:ring-indigo-500 outline-none"
                  onKeyDown={(e) => {
                    if (e.key === 'Enter' && !isGeneratingInline) {
                      handleInlineQuickGenerate();
                    }
                  }}
                />
                <button
                  type="button"
                  onClick={() => handleInlineQuickGenerate()}
                  disabled={isGeneratingInline || !inlineKeywords.trim()}
                  className="px-3 py-2 bg-indigo-600 hover:bg-indigo-700 text-white font-bold text-xs rounded-xl transition flex items-center gap-1 cursor-pointer disabled:opacity-50 whitespace-nowrap shadow-2xs"
                >
                  <Sparkles className={`w-3.5 h-3.5 ${isGeneratingInline ? 'animate-spin' : ''}`} />
                  <span>{isGeneratingInline ? 'Đang tạo...' : 'Tạo nhanh'}</span>
                </button>
              </div>

              {/* Quick topic suggestion tags */}
              <div className="flex flex-wrap gap-1 items-center">
                <span className="text-[10px] text-gray-500 font-medium">Gợi ý:</span>
                {[
                  { label: 'Trì hoãn làm bài', kw: 'trì hoãn làm bài tập về nhà, lướt điện thoại' },
                  { label: 'Mạng xã hội đêm', kw: 'cám dỗ mạng xã hội ban đêm, mất ngủ' },
                  { label: 'Áp lực điểm số', kw: 'áp lực kỳ vọng điểm số, lo âu thi cử' },
                  { label: 'Bất đồng nhóm', kw: 'xung đột ý kiến bài tập nhóm, đùn đẩy trách nhiệm' }
                ].map((tag, idx) => (
                  <button
                    key={idx}
                    type="button"
                    onClick={() => {
                      setInlineKeywords(tag.kw);
                      handleInlineQuickGenerate(tag.kw);
                    }}
                    className="text-[10px] px-2 py-0.5 rounded-lg bg-white hover:bg-indigo-100/60 text-gray-700 border border-indigo-100 font-medium transition cursor-pointer"
                  >
                    {tag.label}
                  </button>
                ))}
              </div>

              {scaffoldSuccessNotice && (
                <div className="p-2 rounded-xl bg-emerald-50 border border-emerald-200 text-emerald-800 text-[11px] font-semibold flex items-center gap-1.5">
                  <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600 flex-shrink-0" />
                  <span>{scaffoldSuccessNotice}</span>
                </div>
              )}
            </div>

            <textarea
              value={rawScript}
              onChange={(e) => setRawScript(e.target.value)}
              rows={16}
              placeholder="Nhập kịch bản, bối cảnh, nhân vật, các lựa chọn và phân cảnh can thiệp..."
              className="w-full text-xs font-mono p-3 rounded-xl border border-gray-200 focus:ring-2 focus:ring-indigo-500 outline-none leading-relaxed resize-none bg-slate-50/50"
            />
          </div>

          <div className="pt-2 border-t border-gray-100 flex items-center justify-between">
            <button
              onClick={handleSaveDraft}
              className="px-4 py-2 bg-gray-100 hover:bg-gray-200 text-gray-700 text-xs font-semibold rounded-lg transition flex items-center gap-1.5"
            >
              <Save className="w-3.5 h-3.5" />
              <span>Lưu nháp</span>
            </button>
            <span className="text-[11px] text-gray-400">
              Trạng thái: <strong>{adminStatus}</strong>
            </span>
          </div>
        </div>

        {/* COLUMN 2: GENERATED GAME SPECIFICATION DSL (Center - 5 cols) */}
        <div className="lg:col-span-5 bg-white p-5 rounded-2xl border border-gray-200 shadow-2xs flex flex-col justify-between space-y-4">
          <div>
            <div className="flex items-center justify-between border-b border-gray-100 pb-3 mb-3">
              <div className="flex items-center gap-2">
                <span className="text-xs font-bold uppercase tracking-wider text-indigo-700">
                  2. Game Specification JSON
                </span>
                {generatedSpec && (
                  <span className="text-[10px] bg-indigo-50 text-indigo-700 px-2 py-0.5 rounded font-mono font-semibold">
                    DSL v{generatedSpec.version}
                  </span>
                )}
              </div>

              <div className="flex items-center gap-1.5">
                <button
                  onClick={handleCopyJson}
                  disabled={!specJsonText}
                  className="p-1.5 text-gray-500 hover:text-gray-800 rounded-lg hover:bg-gray-100 transition"
                  title="Sao chép JSON"
                >
                  {isCopied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
                </button>
                <button
                  onClick={handleDownloadJson}
                  disabled={!specJsonText}
                  className="p-1.5 text-gray-500 hover:text-gray-800 rounded-lg hover:bg-gray-100 transition"
                  title="Tải tệp .json"
                >
                  <Download className="w-3.5 h-3.5" />
                </button>
              </div>
            </div>

            {specJsonText ? (
              <div className="space-y-2">
                <div className="flex items-center justify-between text-[11px] text-gray-500 px-1">
                  <span>Có thể chỉnh sửa trực tiếp JSON bên dưới:</span>
                  <span className="text-indigo-600 font-semibold">Tự động kiểm tra cú pháp</span>
                </div>
                <textarea
                  value={specJsonText}
                  onChange={(e) => handleJsonChange(e.target.value)}
                  rows={16}
                  className="w-full text-xs font-mono p-3 rounded-xl border border-gray-200 bg-slate-900 text-emerald-400 focus:ring-2 focus:ring-indigo-500 outline-none leading-relaxed resize-none"
                />
              </div>
            ) : (
              <div className="h-72 flex flex-col items-center justify-center text-center p-6 border-2 border-dashed border-gray-200 rounded-xl text-gray-400">
                <Sparkles className="w-8 h-8 mb-2 text-gray-300" />
                <p className="text-xs font-medium">Chưa có Game Specification nào.</p>
                <p className="text-[11px] mt-1 text-gray-400">
                  Nhấp vào nút "Phân tích Script → Tạo Game Specification" ở trên để sinh JSON.
                </p>
              </div>
            )}
          </div>

          {generatedSpec && (
            <div className="pt-2 border-t border-gray-100 flex items-center justify-between text-[11px] text-gray-500">
              <span>Scenes: {generatedSpec.scenes?.length || 0}</span>
              <span>Game ID: {generatedSpec.gameId}</span>
            </div>
          )}
        </div>

        {/* COLUMN 3: VALIDATION WARNINGS & PUBLISH GATE (Right - 3 cols) */}
        <div className="lg:col-span-3 bg-white p-5 rounded-2xl border border-gray-200 shadow-2xs flex flex-col justify-between space-y-4">
          <div className="space-y-4">
            <div className="border-b border-gray-100 pb-3">
              <span className="text-xs font-bold uppercase tracking-wider text-gray-700 block">
                3. Cổng kiểm định & Phê duyệt
              </span>
              <span className="text-[10px] text-gray-400">
                Kiểm tra tính toàn vẹn và an toàn trước khi xuất bản
              </span>
            </div>

            {/* Validation Checklist */}
            {validationResult ? (
              <div className="space-y-3">
                <div className="p-3 rounded-xl border text-xs space-y-2">
                  <div className="flex items-center justify-between font-semibold">
                    <span>JSON Schema DSL:</span>
                    {validationResult.schemaValid ? (
                      <span className="text-emerald-600 flex items-center gap-1 font-bold">
                        <CheckCircle2 className="w-3.5 h-3.5" /> Đạt
                      </span>
                    ) : (
                      <span className="text-rose-600 flex items-center gap-1 font-bold">
                        <XCircle className="w-3.5 h-3.5" /> Lỗi
                      </span>
                    )}
                  </div>

                  <div className="flex items-center justify-between font-semibold">
                    <span>Liên kết rẽ nhánh:</span>
                    {validationResult.referencesValid ? (
                      <span className="text-emerald-600 flex items-center gap-1 font-bold">
                        <CheckCircle2 className="w-3.5 h-3.5" /> Hợp lệ
                      </span>
                    ) : (
                      <span className="text-rose-600 flex items-center gap-1 font-bold">
                        <XCircle className="w-3.5 h-3.5" /> Đứt gãy
                      </span>
                    )}
                  </div>

                  <div className="flex items-center justify-between font-semibold">
                    <span>Tiêu chuẩn an toàn:</span>
                    {generatedSpec?.safety?.status === 'approved' ? (
                      <span className="text-emerald-600 flex items-center gap-1 font-bold">
                        <ShieldCheck className="w-3.5 h-3.5" /> An toàn
                      </span>
                    ) : (
                      <span className="text-amber-600 flex items-center gap-1 font-bold">
                        <AlertTriangle className="w-3.5 h-3.5" /> Chờ duyệt
                      </span>
                    )}
                  </div>
                </div>

                {/* Errors list */}
                {validationResult.errors.length > 0 && (
                  <div className="p-3 bg-rose-50 border border-rose-200 rounded-xl text-xs text-rose-800 space-y-1">
                    <span className="font-bold block flex items-center gap-1">
                      <XCircle className="w-3.5 h-3.5 text-rose-600" /> Các lỗi bắt buộc phải sửa:
                    </span>
                    <ul className="list-disc pl-4 space-y-0.5 text-[11px]">
                      {validationResult.errors.map((err, i) => (
                        <li key={i}>{err}</li>
                      ))}
                    </ul>
                  </div>
                )}

                {/* Warnings list */}
                {validationResult.warnings.length > 0 && (
                  <div className="p-3 bg-amber-50 border border-amber-200 rounded-xl text-xs text-amber-800 space-y-1">
                    <span className="font-bold block flex items-center gap-1">
                      <AlertTriangle className="w-3.5 h-3.5 text-amber-600" /> Cảnh báo kiểm duyệt:
                    </span>
                    <ul className="list-disc pl-4 space-y-0.5 text-[11px]">
                      {validationResult.warnings.map((warn, i) => (
                        <li key={i}>{warn}</li>
                      ))}
                    </ul>
                  </div>
                )}
              </div>
            ) : (
              <div className="p-4 bg-gray-50 border border-gray-200 rounded-xl text-xs text-gray-500 text-center">
                Chưa có dữ liệu kiểm định. Vui lòng tạo kịch bản từ AI Studio để bắt đầu kiểm tra.
              </div>
            )}
          </div>

          {/* Workflow Approval Action Buttons */}
          <div className="pt-4 border-t border-gray-100 space-y-2">
            <button
              onClick={handleSubmitReview}
              className="w-full py-2 px-3 bg-white border border-gray-300 hover:bg-gray-50 text-gray-700 text-xs font-semibold rounded-xl transition"
            >
              Gửi kiểm duyệt (Submit Review)
            </button>

            <button
              onClick={handleApprove}
              disabled={!validationResult?.schemaValid || !validationResult?.referencesValid}
              className={`w-full py-2.5 px-3 text-xs font-bold rounded-xl transition flex items-center justify-center gap-1.5 ${
                validationResult?.schemaValid && validationResult?.referencesValid
                  ? 'bg-amber-600 hover:bg-amber-700 text-white cursor-pointer shadow-xs'
                  : 'bg-gray-100 text-gray-400 cursor-not-allowed'
              }`}
            >
              <CheckCircle2 className="w-3.5 h-3.5" />
              <span>Phê duyệt (Approve)</span>
            </button>

            {/* Strict Publish Gate */}
            <button
              onClick={handlePublish}
              disabled={
                !generatedSpec ||
                !validationResult?.isValid ||
                generatedSpec.safety?.status !== 'approved'
              }
              className={`w-full py-3 px-3 text-xs font-bold rounded-xl transition flex items-center justify-center gap-1.5 ${
                generatedSpec &&
                validationResult?.isValid &&
                generatedSpec.safety?.status === 'approved'
                  ? 'bg-emerald-600 hover:bg-emerald-700 text-white cursor-pointer shadow-md'
                  : 'bg-gray-200 text-gray-400 cursor-not-allowed'
              }`}
            >
              <ShieldCheck className="w-4 h-4" />
              <span>Xuất bản ra Runtime (Publish)</span>
            </button>

            {(!validationResult?.isValid || generatedSpec?.safety?.status !== 'approved') && (
              <p className="text-[10px] text-gray-400 text-center italic">
                * Nút xuất bản chỉ mở khi schema đạt 100% và trạng thái an toàn là "approved".
              </p>
            )}
          </div>
        </div>
      </div>

      {/* Modal: Gemini Script Scaffold Generator */}
      <GeminiScriptScaffoldModal
        isOpen={isScaffoldModalOpen}
        onClose={() => setIsScaffoldModalOpen(false)}
        onApplyScaffold={handleApplyScaffold}
        currentMinAge={Number(minAge)}
        currentMaxAge={Number(maxAge)}
      />
    </div>
  );
};
